# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "debian/buster64"

  # Define disk size
  config.disksize.size = '20GB'

  # Disable the default shared folder
  config.vm.synced_folder '.', '/vagrant', disabled: true

  # Work around to enable guest editions and shared folders
  if ENV['FIRST_RUN'] == 'true'
    config.vbguest.auto_update = false
  else
    # Create shared folder
    config.vm.synced_folder "share", "/media/share", create: true, type: "virtualbox"
  end

  # Install web things here
  config.vm.provision "shell", path: "setup.sh"

  # Setup a private network
  config.vm.network "private_network", ip: "10.0.0.10"

  # Setup a public network
  #config.vm.network "public_network"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "1024"

    # Set vCPUs
    vb.cpus = 1
  end
end
