# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/eoan64"

  # Define disk size
  config.disksize.size = '20GB'

  # Disable the default shared folder
  config.vm.synced_folder '.', '/vagrant', disabled: true

  # Create shared folder
  config.vm.synced_folder "share", "/media/share", create: true, type: "virtualbox"

  # Define the nagios server
  config.vm.define "nagios" do |nagios|
    # Setup a private network
    nagios.vm.network "private_network", ip: "10.0.0.10"

    # Install nagios things here
    nagios.vm.provision "shell", path: "setup_nagios.sh"
  end

  # Define a client for nagios
  config.vm.define "client" do |client|
    # Setup a private network
    client.vm.network "private_network", ip: "10.0.0.11"

    # Install client things here
    client.vm.provision "shell", path: "setup_client.sh"
  end

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "1024"

    # Set vCPUs
    vb.cpus = 1
  end
end
