# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "debian/buster64"

  # Set the vm boot timeout value (seconds)
  config.vm.boot_timeout = 600

  # Define disk size
  config.disksize.size = '20GB'

  # Disable the shared folder (it seems to hang and fail)
  config.vm.synced_folder '.', '/vagrant', disabled: true

  # Work around to enable guest editions and shared folders
  if ENV['FIRST_RUN'] == 'true'
    config.vbguest.auto_update = false
  else
    config.vm.synced_folder "share", "/mnt/share", create: true
  end

  if ENV['RUN_FROM_SCRIPT'] != 'true'
    config.vbguest.auto_update = false
  end

  # Enable provisioning with a shell script.
  config.vm.provision "shell", inline: <<-SHELL
    apt update
    apt install xen-system xen-tools lvm2 bridge-utils vim -y
    pvcreate /dev/sdb
    vgcreate vg0 /dev/sdb
    update-grub
  SHELL

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false

    # Customize the amount of memory on the VM:
    vb.memory = "2048"

    # Set vCPUs
    vb.cpus = 2

    # Create a disk if not found
    disk = "lvmdisk.vdi"
    unless File.exist?(disk)
      vb.customize ['createhd', '--filename', disk, '--variant', 'Fixed', '--size', 50 * 1024]
    end

    # Attach the disk to the VM
    vb.customize ['storageattach', :id,  '--storagectl', 'SATA Controller', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', disk]
  end
end